language: generic
sudo: required
services:
  - docker 
  
before_install:
  - docker build -f Dockerfile.dev -t ryanthomas/docker-react .
  
script:
  - docker run -e CI=true ryanthomas/docker-react npm run test